name: waico
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.7
  flutter_ai_toolkit: ^0.9.1
  background_downloader: ^9.2.2
  health: ^13.1.1
  permission_handler: ^11.3.1
  cross_file: ^0.3.4+2
  just_audio: ^0.10.4
  audio_session: ^0.2.2
  provider: ^6.1.5
  sherpa_onnx: ^1.12.6
  archive: ^4.0.7
  record: ^6.0.0
  path_provider: ^2.1.5
  synchronized: ^3.4.0
  device_calendar: ^4.3.3
  flutter_timezone: ^4.1.1
  flutter_mailer: ^3.0.1
  url_launcher: ^6.3.2
  flutter_phone_direct_caller: ^2.2.1
  intl: ^0.20.2
  objectbox: ^4.3.0
  objectbox_flutter_libs: any
  llama_cpp_dart: ^0.1.0
  fl_chart: ^1.0.0
  wakelock_plus: ^1.3.2
  flutter_gemma:
    git:
      url: https://github.com/sitatec/flutter_gemma.git
      ref: mine
  vector_math: ^2.1.4
  shared_preferences: ^2.5.3
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  objectbox_generator: any

dependency_overrides:
  # Override with a sherpa_onnx_android that doesn't content prebuilt native .so libs
  # We will include our own that support GPU inference because the original doesn't
  sherpa_onnx_android:
    git:
      url: https://github.com/sitatec/sherpa-onnx.git
      path: flutter/sherpa_onnx_android

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/exercises/
    - assets/models/silero_vad_v5.onnx
    - assets/translations/


objectbox:
  output_dir: generated

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo-with-slogan.png

  android_12:
    color: "#FFFFFF"
    image: assets/images/logo-with-slogan-android12.png
  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/mascot.png"
  min_sdk_android: 27
  remove_alpha_ios: true